---
title: "p8105_hw5_fy2297"
output: github_document
---

```{r}
# load libraries
library(tidyverse)
library(rvest)
library(httr)
library(purrr)
```

# Problem 1


# Problem 2
```{r}
# import data
url = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"
homicide_df = read_csv(url) %>% 
  janitor::clean_names()
```

```{r echo=FALSE}
# data for raw data description
n_row = nrow(homicide_df)
n_col = ncol(homicide_df)
```
raw data description:
The raw dataset has `r n_col` variables and `r n_row` observations. The main variables are reported date, victim race, sex, age and its corresponding city and state.

```{r}
# data manipulation
homicide_df = 
  homicide_df %>% 
  mutate(
    city_state = paste(city, state, sep = ","),
    disposition = ifelse(disposition == "Closed by arrest", "resolved", "unresolved")
  )
# create a new dataset and find the total number of homicides and the number of unsolved homicides within cities
homicide_summary_df =
  homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    total_homicides = n(),
    unsolved_homicides = sum(disposition == "unresolved")
  )
```

```{r}
# About Baltimore, MD
Baltimore_df =  
  homicide_summary_df %>% 
  filter(city_state == "Baltimore,MD")

test_stats_Baltimore = 
prop.test(
  Baltimore_df$unsolved_homicides,Baltimore_df$total_homicides) %>% 
  broom::tidy()
```
The estimated proportion of unsolved homicides is about 64.6% and the confidence interval is [62.8%, 66.3%].

```{r}
# find statistics for all cities
test_stats_all = 
  homicide_summary_df %>% 
  mutate(
    test_stats = map2(unsolved_homicides, total_homicides, ~prop.test(.x, .y)),
    test_stats = map(test_stats, broom::tidy)
  ) %>% 
  unnest() %>% 
  arrange(estimate) %>% 
  select(
    city_state, estimate, conf.low, conf.high
  )
```




# Problem 3